---
title: "Final Project"
author: Morgan Godley, Priom Mahmud, Qin Xu, Chaobo Yan
output: pdf_document
---

## Model Assumption

$$
\begin{aligned}
y_{ijk} = \mu + \tau_i+\beta_j+ \left(\tau\beta\right)_{ij} +\gamma_k + \epsilon_{ijk}
\end{aligned}
$$

where $\mu$ is the overall mean, $\tau_i$ is the mean of activity (walking and meditation)

```{r}
wm <- read.csv("final_data.csv")
wm$User <- as.factor(wm$User)
wm$Time <- as.factor(wm$Time)
wm$Activity <- as.factor(wm$Activity)
```

### Random effect of not studying the interaction of blocking factor

```{r}
library(lmerTest)
wm_lmer <- lmer(Score ~ Time * Activity + (1|User),
                data = wm,
                contrasts = list(Time = "contr.helmert",
                Activity = "contr.helmert"))
```

```{r}
summary(wm_lmer)
```

```{r}
ranova(wm_lmer)
```

```{r}
layout(matrix(1:6, 2, 3)); par(mar = c(4, 4, 2.5, 1.5))
# Check normality
qqnorm(residuals(wm_lmer))
qqline(residuals(wm_lmer))

#Residuals
plot(wm$Time, rstudent(wm_lmer), main = "Constant Variance - Time") 
plot(wm$Activity, rstudent(wm_lmer), main = "Constant Variance - Activity")
plot(fitted(wm_lmer), resid(wm_lmer), main = "Constant Variance")
#plot(wm_lmer,which=4)
```

```{r}
# Interaction Plot

# Estimate Marginal Means
library(emmeans)
emm_wm_lmer <- emmeans(wm_lmer, ~ Time * Activity) 
emm_df_wm_lmer <- as.data.frame(emm_wm_lmer) #as DF

# Use ggplot2 for the interaction plot
library(ggplot2)
ggplot(emm_df_wm_lmer, aes(x = Time, y = emmean, group = Activity, color = Activity)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Interaction Plot: Time x Activity\nRandom effect of not studying the interaction of blocking factor", 
       y = "Estimated Marginal Mean of Score") +
  theme_minimal()
```

### Fixed effect of not studying the interaction of blocking factor

```{r}
wm_aov <- aov(Score ~ Time * Activity + User,
                data = wm,
                contrasts = list(Time = "contr.helmert",
                Activity = "contr.helmert"))
```

```{r}
summary(wm_aov)
```

```{r}
layout(matrix(1:6, 2, 3)); par(mar = c(4, 4, 2.5, 1.5))
# Check normality
qqnorm(residuals(wm_aov))
qqline(residuals(wm_aov))

# Check constant variance
plot(wm$Time, rstudent(wm_aov), main = "Constant Variance - Time") 
plot(wm$Activity, rstudent(wm_aov), main = "Constant Variance - Activity")
plot(fitted(wm_aov), resid(wm_aov), main = "Constant Variance")
```

```{r}
# Interaction Plot

# Estimate Marginal Means
emm_wm_aov <- emmeans(wm_aov, ~ Time * Activity) 
emm_df_wm_aov <- as.data.frame(emm_wm_aov) #as DF

# Interaction plot
ggplot(emm_df_wm_aov, aes(x = Time, y = emmean, group = Activity, color = Activity)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Interaction Plot: Time x Activity\nFixed effect of not studying the interaction of blocking factor", 
       y = "Estimated Marginal Mean of Score") +
  theme_minimal()
```

### Fixed effect of study the interaction of blocking factor

```{r}
wm_aov2 <- aov(Score ~ Time * Activity * User,
                data = wm,
                contrasts = list(Time = "contr.helmert",
                Activity = "contr.helmert"))
```

```{r}
anova(wm_aov2)
```

```{r}
layout(matrix(1:6, 2, 3)); par(mar = c(4, 4, 2.5, 1.5))
# Check normality
qqnorm(residuals(wm_aov2))
qqline(residuals(wm_aov2))

# Check constant variance
plot(wm$Time, rstudent(wm_aov2), main = "Constant Variance - Time") 
plot(wm$Activity, rstudent(wm_aov2), main = "Constant Variance - Activity")
plot(fitted(wm_aov2), resid(wm_aov2), main = "Constant Variance")
```

```{r, include=FALSE, echo=FALSE}
# Check normality
plot(wm_aov2,which=2)

qqnorm(residuals(wm_aov2))
qqline(residuals(wm_aov2))


```

```{r}
ggplot(wm, aes(x = Time, y = Score, color = Activity, group = Activity)) +
  stat_summary(fun = mean, geom = "point", position = position_dodge(0.2)) +
  stat_summary(fun = mean, geom = "line", position = position_dodge(0.2)) +
  facet_wrap(~ User) +
  labs(title = "Interaction Plot: Time x Activity\nBy Users 1-4") +
  theme_minimal()
```

### Random effect of studying the interaction of blocking factor

```{r}
wm_lmer2 <- lmer(Score ~ Time * Activity
                 + (Time + Activity|User),
                data = wm,
                contrasts = list(Time = "contr.helmert",
                Activity = "contr.helmert"))
```

```{r}
summary(wm_lmer2)
```

```{r}
ranova(wm_lmer2)
```

```{r}
layout(matrix(1:6, 2, 3)); par(mar = c(4, 4, 2.5, 1.5))
# Check normality
qqnorm(residuals(wm_lmer2))
qqline(residuals(wm_lmer2))

# Check constant variance
plot(wm$Time, rstudent(wm_lmer2), main = "Constant Variance - Time") 
plot(wm$Activity, rstudent(wm_lmer2), main = "Constant Variance - Activity")
plot(fitted(wm_lmer2), resid(wm_lmer2), main = "Constant Variance")
```

```{r}
# Interaction Plot

# Estimate Marginal Means
emm_wm_lmer2 <- emmeans(wm_lmer2, ~ Time * Activity)
emm_df_wm_lmer2 <- as.data.frame(emm_wm_lmer2) # as DF

# Interaction plot
ggplot(emm_df_wm_lmer2, aes(x = Time, y = emmean, group = Activity, color = Activity)) +
  geom_point(size = 3) +
  geom_line() +
  labs(title = "Interaction Plot: Time x Activity\nRandom effect of studying the interaction of blocking factor", 
       y = "Estimated Marginal Mean of Score") +
  theme_minimal()
```

```{r}
library(pwr)
# k - 4 groups
# n - 64 total samples divied by 4 groups
# f - Cohen's f = delta / std_dev; std_dev assumed to be 2
# alpha - 0.05

power01 <- pwr.anova.test(k=4, n=64/4, f=0.1/2, sig.level=0.05)
power1 <- pwr.anova.test(k=4, n=64/4, f=1/2, sig.level=0.05)
power3 <- pwr.anova.test(k=4, n=64/4, f=3/2, sig.level=0.05)
power5 <- pwr.anova.test(k=4, n=64/4, f=5/2, sig.level=0.05)

print("Power at Difference in Mean 0.1")
power01
print("\nPower at Difference in Mean 1")
power1
print("\nPower at Difference in Mean 3")
power3
print("\nPower at Difference in Mean 5")
power5
```